import AtividadeJanelas3.model.Listas;
import AtividadeJanelas3.model.Cadastros;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaInicial extends javax.swing.JFrame {

    private final List<Cadastros> cadastrosList = Listas.ListarCadastros();
    
    private final String[] tableColumns = {"Paciente", "CPF", "Telefone", "Data", "Já era paciente?", "Consulta realizada"};
    
    DefaultTableModel tableModel = new DefaultTableModel(tableColumns, 0);
    
    public TelaInicial() {
        initComponents();
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConsultas = new javax.swing.JTable();
        NovaC = new javax.swing.JButton();
        ExcluirC = new javax.swing.JButton();
        FinalizarC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Boas vindas ao sistema de agendamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        tblConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Paciente", "CPF", "Telefone", "Data", "Já era paciente?", "Consulta realizada"
            }
        ));
        jScrollPane2.setViewportView(tblConsultas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addContainerGap())
        );

        NovaC.setText("Nova Consulta");
        NovaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovaCActionPerformed(evt);
            }
        });

        ExcluirC.setText("Excluir Consulta");
        ExcluirC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirCActionPerformed(evt);
            }
        });

        FinalizarC.setText("Finalizar Consulta");
        FinalizarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NovaC)
                        .addGap(46, 46, 46)
                        .addComponent(ExcluirC)
                        .addGap(55, 55, 55)
                        .addComponent(FinalizarC)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovaC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExcluirC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FinalizarC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void atualizarTabela(){
     
        if(!cadastrosList.isEmpty()){
         
            Cadastros cadastro;
         
            for (int i = 0; i < cadastrosList.size(); i++) {
             
                cadastro = cadastrosList.get(i);
             
                String[] rowData = {cadastro.getNome(), cadastro.getCPF(), cadastro.getTelefone(), cadastro.getData(), cadastro.getEraPaciente(), cadastro.getConsReal()};
             
                tableModel.addRow(rowData);
            }
         
            tblConsultas.setModel(tableModel);
        }else{
            tableModel = new DefaultTableModel(tableColumns, 0);
            tblConsultas.setModel(tableModel);
        }     
    }
    
    private void ExcluirCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirCActionPerformed
        excluirConsulta();
    }//GEN-LAST:event_ExcluirCActionPerformed

    private void NovaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovaCActionPerformed
        TelaCadastro tCadastro = new TelaCadastro();
        tCadastro.setVisible(true);
    }//GEN-LAST:event_NovaCActionPerformed

    private void FinalizarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarCActionPerformed
        
        int posConsulta = tblConsultas.getSelectedRow();
        
        if (posConsulta != -1){
            Cadastros cadastroSelect = cadastrosList.get(posConsulta);
            TelaFinalizacao tFinal = new TelaFinalizacao(cadastroSelect);
            tFinal.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma consulta", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_FinalizarCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExcluirC;
    private javax.swing.JButton FinalizarC;
    private javax.swing.JButton NovaC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblConsultas;
    // End of variables declaration//GEN-END:variables

    private void excluirConsulta(){
     
        int posConsulta = tblConsultas.getSelectedRow();
        
        if(posConsulta >= 0){
        
            String[] options = { "Sim", "Não" };
         
            int deletar = JOptionPane.showOptionDialog(
                    rootPane,
                    "Tem certeza que deseja excluir?", 
                    "Exclusão de Consulta", 
                    JOptionPane.DEFAULT_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, 
                    null, 
                    options, 
                    options[0]
            );
         
            if(deletar == 0){
                DefaultTableModel tabela = (DefaultTableModel) tblConsultas.getModel();
                tabela.removeRow(posConsulta);    
                cadastrosList.remove(posConsulta);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma consulta.");
        }
    }  
}
