
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author RaquelNunes
 */
public class TelaCalculoCalorico extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalculoCalorico
     */
    public TelaCalculoCalorico() {
        initComponents();
        
        txtGastobasal.setText("");
        txtGastototal.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelpeso2 = new javax.swing.JLabel();
        jLabelaltura2 = new javax.swing.JLabel();
        jLabelidade = new javax.swing.JLabel();
        jLabelnvlatv = new javax.swing.JLabel();
        jLabelgastobasal = new javax.swing.JLabel();
        jLabelgastototal = new javax.swing.JLabel();
        jButtoncalcular2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbNivelAtividade = new javax.swing.JComboBox<>();
        txtGastobasal = new javax.swing.JLabel();
        txtGastototal = new javax.swing.JLabel();
        txtPesoGastoCalorico = new javax.swing.JTextField();
        txtAlturaGastoCalorico = new javax.swing.JTextField();
        txtIdadeGastoCalorico = new javax.swing.JTextField();
        jrbMulher = new javax.swing.JRadioButton();
        jrbHomem = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gasto Calórico");

        jLabelpeso2.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabelpeso2.setText("Peso (Kg):");

        jLabelaltura2.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabelaltura2.setText("Altura (cm):");

        jLabelidade.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabelidade.setText("Idade:");

        jLabelnvlatv.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabelnvlatv.setText("Nível de Atividade:");

        jLabelgastobasal.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabelgastobasal.setText("Gasto Basal:");

        jLabelgastototal.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabelgastototal.setText("Gasto Total:");

        jButtoncalcular2.setFont(new java.awt.Font("Dialog", 0, 25)); // NOI18N
        jButtoncalcular2.setText("Calcular");
        jButtoncalcular2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncalcular2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 25)); // NOI18N
        jLabel1.setText("Cálculo de Gasto Calórico");

        cmbNivelAtividade.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        cmbNivelAtividade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nível de Atividade", "Sedentário", "Leve (exercício leve 1 a 3 dias/semana)", "Moderado (exercício moderado 3 a 5 dias/semana)", "Ativo (exercício pesado 5 a 6 dias/semana)", "Extremamente ativo (exercício pesado diário)" }));
        cmbNivelAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNivelAtividadeActionPerformed(evt);
            }
        });

        txtGastobasal.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtGastobasal.setText("jLabel2");

        txtGastototal.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtGastototal.setText("jLabel3");

        txtPesoGastoCalorico.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtPesoGastoCalorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoGastoCaloricoActionPerformed(evt);
            }
        });

        txtAlturaGastoCalorico.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        txtIdadeGastoCalorico.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        buttonGroup1.add(jrbMulher);
        jrbMulher.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jrbMulher.setText("MULHER");

        buttonGroup1.add(jrbHomem);
        jrbHomem.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jrbHomem.setText("HOMEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtoncalcular2)
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelnvlatv)
                                .addGap(18, 18, 18)
                                .addComponent(cmbNivelAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelgastobasal)
                                    .addComponent(jLabelgastototal))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtGastototal, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(txtGastobasal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelpeso2)
                                    .addComponent(jLabelaltura2)
                                    .addComponent(jLabelidade))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPesoGastoCalorico, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                    .addComponent(txtAlturaGastoCalorico)
                                    .addComponent(txtIdadeGastoCalorico)))
                            .addComponent(jrbMulher)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jrbHomem)
                            .addComponent(jLabel1))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbMulher)
                    .addComponent(jrbHomem))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelpeso2)
                    .addComponent(txtPesoGastoCalorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelaltura2)
                    .addComponent(txtAlturaGastoCalorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelidade)
                    .addComponent(txtIdadeGastoCalorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelnvlatv)
                    .addComponent(cmbNivelAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jButtoncalcular2)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelgastobasal)
                    .addComponent(txtGastobasal))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelgastototal)
                    .addComponent(txtGastototal))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesoGastoCaloricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoGastoCaloricoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoGastoCaloricoActionPerformed

    private void jButtoncalcular2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncalcular2ActionPerformed
        // TODO add your handling code here:
        
         // ENTRADAS NA TELA DE GASTO CALÓRICO
         String alturaGastoCalorico = txtAlturaGastoCalorico.getText() .replace(",", ".");
         String pesoGastoCalorico = txtPesoGastoCalorico.getText() .replace(",", ".");
         
         // Declaração das variáveis fora do bloco try
            double calcBasal = 0.0;
            double calcTotal = 0.0;
    
         //BOTÃO Mulher~Homem
         if (jrbMulher.isSelected()) {} 
         else {}
         
         try {

         int idade = Integer.parseInt(txtIdadeGastoCalorico.getText());
         
         // CONVERSAO PARA DOUBLE
            Double alturaGc = Double.parseDouble(alturaGastoCalorico);
            Double pesoGc = Double.parseDouble(pesoGastoCalorico);

         // VERIFICA SE O USUÁRIO INSERIU VALORES VÁLIDOS NOS CAMPOS (= 0)
          if (pesoGc <= 0 || alturaGc <= 0 || idade <= 0) {
                JOptionPane.showMessageDialog(this, "Por favor, insira valores válidos.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
          // VERIFICA SE O USUÁRIO SELECIONOU UM SEXO
            if (!jrbMulher.isSelected() && !jrbHomem.isSelected()) {
            JOptionPane.showMessageDialog(this, "Selecione o sexo.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
          // VERIFICA SE O USUÁRIO SELECIONOU O NÍVEL DE ATIVIDADE 
        if (cmbNivelAtividade.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Selecione o nível de atividade.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // CÁLCULO DO GASTO CALÓRICO BASAL
        if (jrbHomem.isSelected()) {
            calcBasal = 66 + (13.8 * pesoGc) + (5 * alturaGc * 100) - (6.8 * idade);
        } else {
            calcBasal = 655 + (9.6 * pesoGc) + (1.9 * alturaGc * 100) - (4.7 * idade);
        }  
         // CÁLCULO DO GASTO CALÓRICO TOTAL COM BASE NO NÍVEL DE ATIVIDADE
        double nivelAtividade;
        nivelAtividade = switch (cmbNivelAtividade.getSelectedIndex()) {
                 case 1 -> 1.2;
                 case 2 -> 1.375;
                 case 3 -> 1.55;
                 case 4 -> 1.725;
                 case 5 -> 1.9;
                 default -> 1.0;
             };  
        calcTotal = calcBasal * nivelAtividade;
         
        } catch (NumberFormatException e) {
           JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos com valores válidos.", "Erro", JOptionPane.ERROR_MESSAGE);
        }

         // SAIDA
        txtGastobasal.setText(String.format("%.2f kcal", calcBasal));
        txtGastototal.setText(String.format("%.2f kcal", calcTotal));  
    }//GEN-LAST:event_jButtoncalcular2ActionPerformed

    private void cmbNivelAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNivelAtividadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNivelAtividadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculoCalorico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbNivelAtividade;
    private javax.swing.JButton jButtoncalcular2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelaltura2;
    private javax.swing.JLabel jLabelgastobasal;
    private javax.swing.JLabel jLabelgastototal;
    private javax.swing.JLabel jLabelidade;
    private javax.swing.JLabel jLabelnvlatv;
    private javax.swing.JLabel jLabelpeso2;
    private javax.swing.JRadioButton jrbHomem;
    private javax.swing.JRadioButton jrbMulher;
    private javax.swing.JTextField txtAlturaGastoCalorico;
    private javax.swing.JLabel txtGastobasal;
    private javax.swing.JLabel txtGastototal;
    private javax.swing.JTextField txtIdadeGastoCalorico;
    private javax.swing.JTextField txtPesoGastoCalorico;
    // End of variables declaration//GEN-END:variables
}
