/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mercado.estoque.view;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import mercado.dao.FornecedorDAO;
import mercado.dao.FornecedorProdutoDAO;
import mercado.dao.ProdutoDAO;
import mercado.model.Fornecedor;
import mercado.model.FornecedorProduto;
import mercado.model.Produto;
import mercado.view.Estoque;

/**
 *
 * @author ygor_
 */
public class AlteraProduto extends javax.swing.JFrame {

    /**
     * Creates new form AlteraProduto
     */
    public AlteraProduto() {
        initComponents();
        preencheFornecedor();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JFormattedTextField();
        lblQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        lblFornecedor = new javax.swing.JLabel();
        cbFornecedor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Alterar Produto");

        lblNome.setText("Nome produto:");

        lblMarca.setText("Marca:");

        lblPreco.setText("Preço unidade:");

        lblQuantidade.setText("Quantidade:");

        lblFornecedor.setText("Fornecedor:");

        jLabel1.setText("Descrição do produto:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMarca)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addGap(65, 65, 65))
                            .addComponent(txtNome)
                            .addComponent(txtMarca)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPreco)
                                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQuantidade)
                                    .addComponent(txtQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))))
                        .addComponent(lblFornecedor)
                        .addComponent(txtId))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(cbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo)
                    .addComponent(txtId))
                .addGap(18, 18, 18)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPreco)
                            .addComponent(lblQuantidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        btnSair.setText("CANCELAR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnSair))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        new Estoque().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if(verificaCampos() == true){
            alterarEstoque();
        }
        new Estoque().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlteraProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlteraProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlteraProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlteraProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlteraProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Fornecedor> cbFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JLabel txtId;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtPreco;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables

public boolean verificaCampos() {
    try {
        // Verifica se os campos de texto estão vazios
        if (txtNome.getText().trim().isEmpty()) {
            mostrarMensagem("Campo NOME vazio.");
            return false;
        }
        else if (txtMarca.getText().trim().isEmpty()) {
            mostrarMensagem("Campo MARCA vazio.");
            return false;
        }
        else if (txtQuantidade.getText().trim().isEmpty()) {
            mostrarMensagem("Campo QUANTIDADE vazio.");
            return false;
        }
        else if(cbFornecedor.getSelectedIndex() == -1){
           mostrarMensagem("Selecione um fornecedor.");
        }
        else if (txtDescricao.getText().trim().isEmpty()) {
            mostrarMensagem("Campo DESCRIÇÃO precisa ser preenchido.");
            return false;
        }else{
        
        try {
            Double.parseDouble(txtPreco.getText().trim());
        } catch (NumberFormatException e) {
            mostrarMensagem("Campo PREÇO deve ser um número válido.");
            return false;
        }

        if (txtQuantidade.getText().trim().isEmpty()) {
            mostrarMensagem("Campo QUANTIDADE vazio.");
            return false;
        }
        // Verifica se a quantidade é válida
        int qtd = Integer.parseInt(txtQuantidade.getText().trim());
        if (qtd < 1) {
            mostrarMensagem("A quantidade deve ser maior que zero.");
            return false;
        }
        }
        // Todos os campos são válidos
        return true;

    } catch (NumberFormatException e) {
        mostrarMensagem("A quantidade precisa ser informada corretamente.");
        return false;
    }
}

private void mostrarMensagem(String mensagem) {
    JOptionPane.showMessageDialog(rootPane, mensagem);
}
    
private void alterarEstoque(){
  // Criar conversor de vírgula por ponto.
    FornecedorProdutoDAO fpDao = new FornecedorProdutoDAO();
    ProdutoDAO pDao = new ProdutoDAO();
    
    // Obter o ID do produto a partir do campo de texto txtId
    int produtoId = Integer.parseInt(txtId.getText());
    
    // Buscar o produto pelo ID
    Produto p = pDao.BuscarProdutoId(produtoId);
    
    // Obter o fornecedor selecionado no JComboBox
    Fornecedor f = (Fornecedor) cbFornecedor.getSelectedItem();
    
    // Buscar o objeto FornecedorProduto pelo ID do produto e do fornecedor
    FornecedorProduto fp = fpDao.BuscarFPId(produtoId, f.getId());
   
    // Atualizar os campos do produto
    p.setNome(txtNome.getText());
    p.setMarca(txtMarca.getText());
    p.setDescricao(txtDescricao.getText());

    // Atualizar a quantidade e o preço no objeto FornecedorProduto
    int qtd = Integer.parseInt(txtQuantidade.getText().trim());
    BigDecimal preco = new BigDecimal(txtPreco.getText());
    fp.setQuantidade(qtd);
    fp.setPreco(preco);
    
    // Atualizar o produto e o FornecedorProduto no banco de dados
    pDao.atualizar(p);
    fpDao.atualizar(fp);
    
    limpaDados();
    JOptionPane.showMessageDialog(rootPane,"Dados atualizados.");
}

 private void preencheFornecedor(){
        FornecedorDAO fDao = new FornecedorDAO();
        List<Fornecedor> Fornecedor = fDao.ListarFornecedor();
        
        for(Fornecedor f : Fornecedor){
            cbFornecedor.addItem(f);
        } 
    }
 
 
 public void recebeObjEstoque(List<Object> rowData){
     FornecedorDAO fDao = new FornecedorDAO();
     ProdutoDAO pDao = new ProdutoDAO();
         if (rowData != null && !rowData.isEmpty()) {
        // Supondo que você conheça a ordem e o tipo dos dados
             int idProduto = Integer.parseInt(String.valueOf(rowData.get(0))); // Converter para int
             String nomeProduto = (String) rowData.get(1);
             String marcaProduto = (String) rowData.get(2);
             BigDecimal precoProduto = new BigDecimal(String.valueOf(rowData.get(3))); // Converter para BigDecimal
             int quantidadeProduto = Integer.parseInt(String.valueOf(rowData.get(4))); // Converter para int
             String nomeFornecedor = (String) rowData.get(5);

            
            Fornecedor f = fDao.buscaFornecedorNome(nomeFornecedor);
            String descricao = pDao.BuscarDescricaoId(idProduto);
        // Faça o que for necessário com os dados
            txtId.setText(String.valueOf(idProduto));
            txtNome.setText(nomeProduto);
            txtMarca.setText(marcaProduto);
            txtPreco.setText(precoProduto.toString());
            txtQuantidade.setText(String.valueOf(quantidadeProduto));
            txtDescricao.setText(descricao);
            selecionarFornecedor(f);
    } else {
        JOptionPane.showMessageDialog(null, "Dados da linha selecionada são inválidos.");
         }   
 }
    private void selecionarFornecedor(Fornecedor fornecedor) {
    ComboBoxModel<Fornecedor> model = cbFornecedor.getModel();
    int size = model.getSize();
    
    for (int i = 0; i < size; i++) {
        Fornecedor f = model.getElementAt(i);
        if (f.equals(fornecedor)) {
            cbFornecedor.setSelectedIndex(i);
            return;
        }
    }}

 private void limpaDados(){
     txtNome.setText("");
     txtMarca.setText("");
     txtDescricao.setText("");
     txtPreco.setText("");
     txtQuantidade.setText("");
     cbFornecedor.setSelectedIndex(-1);

     txtNome.requestFocus();
 }
 

}
